version: "3.7"
services:
  lookup:
    image: lookup-api:latest
    container_name: lookup-api
    build: .
    restart: always
    ports:
      - 6041:6041
#    volumes:
#      - /home/development/certificate:/home
networks:
  default:
    external:
      name: rsis-network