#spring.application.name=rsis
#server.port=6041
##used to connect with db and other application local connection
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.show-sql=true
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/resis_db
#spring.datasource.username=postgres
#spring.datasource.password=admin@123
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.show-sql=true
#spring.datasource.url=jdbc:postgresql://102.214.45.147:5440/rsis_db
#spring.datasource.username=ortamisemim
#spring.datasource.password=ortamisemimDb@2021
#spring.datasource.driver-class-name=org.postgresql.Driver

